#!/usr/bin/env php
<?php
/**
 * Saves mails sent from PHP as textfiles. Perfect for testing email.
 * Add the following to your php.ini:
 * sendmail_path = php-sendmail
 * 
 * Heavily inspired by http://drupal4hu.com/node/55
 */

$dir = "/tmp/phpmails";
if (!is_dir($dir)) {
  mkdir($dir);
}

$input = file_get_contents('php://stdin');
preg_match('|^To: (.*)|', $input, $matches);
$filename = isset($matches[1]) ? $matches[1] : 'no-recepient_';
$t = $dir . '/' . date('ymd\TH:i:s') .''. $filename .'.txt';
file_put_contents($t, $input);